export const assetFieldNames = [
  "primaryArtist",
  "secondaryArtist",
  "isrcCode",
  "title",
  "pYear",
  "pName",
  "subtitle",
  "duration",
  "assetNotes",
  "recordingCountry",
  "medley",
  "containsSample",
  "recordingDate",
  "recordingYear",
  "genreText",
  "language",
  "numberOfFeatContributors",
  "featPerformLineUpComplete",
  "numberOfNonFeatPerformers",
  "contentType",
  "isRemastered",
  "comissioningCountry",
  "displayArtistName",
  "cYear",
  "createdDate",
  "isActive",
];

export const productFieldNames = [
  "Product",
  "FugaID",
  "Primary Artist(s)",
  "Featuring Artist(s)",
  "PYEAR",
  "PNAME",
  "CYEAR",
  "CNAME",
  "Album Title",
  "Record Label",
  "Main Release Date",
  "Catalog Number",
  "Media/Format",
  "Compilation",
  "Barcode/UPC/EAN",
  "SCPP ID",
  "Display Artist",
  "Track No (Asset # on Volume)",
  "Volume Number",
];

export const assetFieldFormatMap: Record<string, string> = {
  fugaAssetId: "number",
  primaryArtist: "string",
  secondaryArtist: "string",
  isrcCode: "ISRC",
  title: "string",
  pYear: "string",
  pName: "year (YYYY)",
  subtitle: "string",
  duration: "number",
  assetNotes: "string",
  recordingCountry: "ISO country code",
  medley: "N/A",
  containsSample: "N/A",
  recordingDate: "date (YYYY-MM-DD)",
  recordingYear: "year (YYYY)",
  genreText: "string",
  language: "ISO language code",
  numberOfFeatContributors: "number",
  featPerformLineUpComplete: "N/A",
  numberOfNonFeatPerformers: "number",
  contentType: "string",
  isRemastered: "N/A",
  comissioningCountry: "ISO country code",
  displayArtistName: "string",
  cYear: "year (YYYY)",
};

export const productFieldFormatMap: Record<string, string> = {
  "Product": "N/A",
  "FugaID": "number",
  "Primary Artist(s)": "string",
  "Featuring Artist(s)": "string",
  "PYEAR": "year (YYYY)",
  "PNAME": "string",
  "CYEAR": "year (YYYY)",
  "CNAME": "string",
  "Album Title": "string",
  "Record Label": "string",
  "Main Release Date": "date (YYYY-MM-DD)",
  "Catalog Number": "string",
  "Media/Format": "string",
  "Compilation": "Yes/No (0/1)",
  "Barcode/UPC/EAN": "UPC",
  "SCPP ID": "number",
  "Display Artist": "string",
  "Track No (Asset # on Volume)": "number",
  "Volume Number": "number",
};

export const formatValues = [
  "UPC",
  "IPN",
  "number",
  "string",
  "year (YYYY)",
  "ISRC",
  "ISO country code",
  "date (YYYY-MM-DD)",
  "ISO language code",
];

export const validationRules = [
  "Mandatory",
  "Range=1-300 characters",
  "Range=1-5 characters",
  "Date=1900-current year + 1",
  "Date>=RH Ownership start year",
  "Boolean=Yes/No (0/1)",
  "Range=1-10 seconds",
  "Already exists in catalog",
  "Date>=PYEAR_asset",
  "Date>=PYEAR_product",
  "Match predefined list",
  "≥ count of CONTRACTED_FEATURED / OTHER_FEATURED contributors",
  "Match: track, music_video, ringtone, production, trailer, classical_track; 'audio' maps to 'track'",
  "Duplicate: If same ISRC repeated in xls rows with different data, later row overrides",
  "number=0",
  "Unknown=acceptable",
  "is NOT UNKNOWN",
  "Value='Unreleased'",
  "Match: SINGLE, EP, ALBUM, BOX-SET, VIDEO",
  "Match: CONTRACTED_FEATURED, NON_FEATURED, OTHER_FEATURED",
  "Match: ACOUSTIC_GUITAR, BACKING_VOCALS, BASS_GUITAR, CONDUCTOR, CELLO, CLARINET, DJ, DOUBLE_BASS, DRUMS, ELECTRIC_GUITAR, ENGINEER, GUITAR, HARMONICA, INSTRUMENTS, KEYBOARDS, LEAD_VOCALS, ORGAN, PERCUSSION, PIANO, PRODUCER, PROGRAMMER, RAPPER, SAXOPHONE, SYNTHESIZER, TROMBONE, TRUMPET, VIOLA, VIOLIN, VOCAL_EFFECTS, VOCALS, WURLITZER_ORGAN",
  "Match: RH name in NRP",
  "Content type: IS NOT classical track",
  "Content type: IS NOT music video",
  "Content type: IS NOT production",
  "Content type: IS NOT ringtone",
  "Content type: IS NOT track",
  "Content type: IS NOT trailer",
];

